name       : wiredtiger
version    : 3.2.1
release    : 10
source     :
    - git|https://github.com/wiredtiger/wiredtiger.git : 3.2.1
license    :
    - Apache-2.0
    - BSD-3-Clause
    - GPL-2.0-or-later
    - MIT
    - Public-Domain
component  : programming
clang      : yes
libsplit   : no
summary    : High performance, NoSQL extensible platform for data management
description: |
    WiredTiger is an high performance, scalable, production quality, NoSQL, Open Source extensible platform for data management.
builddeps  :
    - pkgconfig(liblz4)
    - leveldb-devel
    - snappy-devel
setup      : |
    %autogen --disable-static \
        --enable-lz4 \
        --enable-leveldb \
        --with-builtins=snappy,zlib
build      : |
    %make
install    : |
    %make_install
#check      : |
#    %make check
