name       : wiredtiger
version    : 6.0.1
release    : 17
source     :
    - git|https://github.com/wiredtiger/wiredtiger : mongodb-6.0.1
license    :
    - Apache-2.0
    - BSD-3-Clause
    - GPL-2.0-or-later
    - MIT
    - Public-Domain
component  : programming
clang      : yes
libsplit   : no
summary    : High performance, NoSQL extensible platform for data management
description: |
    WiredTiger is an high performance, scalable, production quality, NoSQL, Open Source extensible platform for data management.
builddeps  :
    - pkgconfig(liblz4)
    - pkgconfig(libsodium)
    - pkgconfig(libzstd)
    - rsync
    - snappy-devel
setup      : |
    %cmake_ninja \
        -DCMAKE_CXX_STANDARD=17 \
        -DHAVE_BUILTIN_EXTENSION_LZ4=ON \
        -DHAVE_BUILTIN_EXTENSION_SNAPPY=ON \
        -DHAVE_BUILTIN_EXTENSION_SODIUM=ON \
        -DHAVE_BUILTIN_EXTENSION_ZLIB=ON \
        -DHAVE_BUILTIN_EXTENSION_ZSTD=ON \
        -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %make check
