name       : wiredtiger
version    : 2.9.3
release    : 2
source     :
    - https://github.com/wiredtiger/wiredtiger/releases/download/2.9.3/wiredtiger-2.9.3.tar.bz2 : 2502a90d6b3d3cae0b1bf221cbfe13999d3bcb7f8bb9fa795ad870be4fc0e1e7
license    :
    - Apache-2.0
    - BSD-3-Clause
    - GPL-2.0
    - MIT
    - Public-Domain
component  : programming
libsplit   : no
summary    : High performance, NoSQL extensible platform for data management
description: |
    WiredTiger is an high performance, scalable, production quality, NoSQL, Open Source extensible platform for data management.WiredTiger is an high performance, scalable, production quality, NoSQL, Open Source extensible platform for data management.WiredTiger is an high performance, scalable, production quality, NoSQL, Open Source extensible platform for data management.
builddeps  :
    - pkgconfig(liblz4)
    - leveldb-devel
    - snappy-devel
setup      : |
    %configure --disable-static \
            --enable-lz4 \
            --enable-leveldb \
            --with-builtins=snappy,zlib
build      : |
    %make
install    : |
    %make_install
check      : |
    #Last test fails
    %make check || :
