name       : wiredtiger
version    : 3.3.0
release    : 13
source     :
    - git|https://github.com/wiredtiger/wiredtiger : mongodb-4.2.11
license    :
    - Apache-2.0
    - BSD-3-Clause
    - GPL-2.0-or-later
    - MIT
    - Public-Domain
component  : programming
clang      : yes
libsplit   : no
summary    : High performance, NoSQL extensible platform for data management
description: |
    WiredTiger is an high performance, scalable, production quality, NoSQL, Open Source extensible platform for data management.
builddeps  :
    - pkgconfig(liblz4)
    - pkgconfig(libzstd)
    - snappy-devel
setup      : |
    %autogen --disable-static \
        --enable-lz4 \
        --with-builtins=snappy,zlib,zstd
build      : |
    %make
install    : |
    %make_install
#check      : |
#    %make check
